services:
  - type: web
    name: voting-app-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: voting-app-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: voting-app-db
    databaseName: voting_app
    user: voting_app_user
    plan: free 